### ISSUE TITLE
Can these files be removed from the repo?

### ISSUE THREAD

**Issue by chadagreene** [alex-s-gardner/GEMB#10]
There are a few files in the repo that don't appear to serve a purpose, or can't be used due to dependencies. @NJSchlegel Can you offer guidance on which of these files can be removed from the repo? 

1.  `flux_batchRun.PBS`
2. `modelSettings.asv` 
3. `testGEMBISSM` (requires `xy2ll`, `triangle`, `setflowequation`, etc) 
4. `loadMetData` this function wants to either load files like `D_1_daily_met_data.mat` which don't exist in the repo, or call a `metDataCreate.m` function, which also doesn't exist in the repo. This one's a bit weird too, because it includes `longwaveDn` as a subfunction, which seems like it would be a fine standalone function but isn't used by anything else in GEMB as far as I can tell.

**Comment by alex-s-gardner** [comment]
1. flux_batchRun.PBS can be deleted... that's from when I was at Michigan
2. modelSettings.asv is a autosave file and can be deleted 
4. These functions are for working with input data and can be removed from the repo.

**Comment by chadagreene** [comment]
Thanks @alex-s-gardner. Did you mean 3 & 4 can be removed?

**Comment by alex-s-gardner** [comment]
This is what I see when I hit the edit button... very strange that  it keeps updating 4 to 3

<img width="788" alt="Screenshot 2024-07-16 at 10 26 02 AM" src="https://github.com/user-attachments/assets/759bb108-5f20-4c15-b71f-1c148a4b9502">

**Comment by alex-s-gardner** [comment]
3 is all Nicole

**Comment by chadagreene** [comment]
> This is what I see when I hit the edit button... very strange that it keeps updating 4 to 3

Yeah, markdown is weird, once it thinks you've got an enumerated list, it will automatically overwrite any number you try to write.  

5. 
5. 
5. 
5. 
5. 

And here's what I wrote: 
<img width="812" alt="Screenshot 2024-07-16 at 10 30 32 AM" src="https://github.com/user-attachments/assets/6aafec6c-3cdf-4ed0-80b4-0fe6620dcef2">

**Comment by NJSchlegel** [comment]
I would like to keep testGEMBISSM in the repo.  I want to make it so one can turn the ISSM dependency off, but also have a test so we can test reproducibility.  If this means putting it in the ISSMclasses or a test directory of some sort that is fine also.  I can work to remove as much of the issm dependency as possible.  Right now, xy2ll I can add to the ISSM classes.  The other should not trigger a dependency unless ISSM_compare is true.

**Comment by NJSchlegel** [comment]
testGEMBISSM runs GEMB.  If ISSM_compare is true, it also runs an ISSM run in parallel and compares the results.  If ISSM_compare is false, it just runs the GEMB test program using Greenland input.
