### ISSUE TITLE
densification calculation comment/warning

### ISSUE THREAD

**Issue by chadagreene** [alex-s-gardner/GEMB#17]
A [comment at the top of the `densification` function](https://github.com/alex-s-gardner/GEMB/blob/3411dfbbf05307f751ca366a4094765fae5e6c9d/GEMB/densification.m#L3) reads: 
```matlab
% THIS NEEDS TO BE DOUBLE CHECKED AS THERE SEEMS TO BE LITTLE DENSIFICATION IN THE MODEL OUTOUT [MAYBE COMPATION IS COMPENSATED FOR BY TRACES OF SNOW???]
```
Is this still a concern, or can I remove the comment?

**Comment by alex-s-gardner** [comment]
if @NJSchlegel concurs, this can be removed

**Comment by NJSchlegel** [comment]
Yes, I am ok with removing this comment.
