### ISSUE TITLE
Ambiguous references in turbulentFlux

### ISSUE THREAD

**Issue by chadagreene** [alex-s-gardner/GEMB#18]
The `turbulentFlux` function [references Bougamont 2006](https://github.com/alex-s-gardner/GEMB/blob/3411dfbbf05307f751ca366a4094765fae5e6c9d/GEMB/turbulentFlux.m#L36), but the Gardner et al. 2023 paper references only the following two Bougamont papers: 

> Bougamont, M. and Bamber, J. L.: A surface mass balance model for the Greenland Ice Sheet, J. Geophys. Res.-Earth Surf., 110, F04018, https://doi.org/10.1029/2005JF000348, 2005. 
> 
> Bougamont, M., Bamber, J. L., Ridley, J. K., Gladstone, R. M., Greuell, W., Hanna, E., Payne, A. J., and Rutt, I.: Impact of model physics on estimating the surface mass balance of the Greenland Ice Sheet, Geophys. Res. Lett., 34, L17501, https://doi.org/10.1029/2007GL030700, 2007. 

The function also references [Patterson 1998](https://github.com/alex-s-gardner/GEMB/blob/3411dfbbf05307f751ca366a4094765fae5e6c9d/GEMB/turbulentFlux.m#L81), which I can't find references for in Gardner 2023 or Gardner 2010. 

And there's a reference to [Wright 1997](https://github.com/alex-s-gardner/GEMB/blob/3411dfbbf05307f751ca366a4094765fae5e6c9d/GEMB/turbulentFlux.m#L99), but both of the Wright papers referenced in Gardner 2023 are from the 2000's. 

There's also a reference to[ Dingman 2002](https://github.com/alex-s-gardner/GEMB/blob/3411dfbbf05307f751ca366a4094765fae5e6c9d/GEMB/turbulentFlux.m#L12), which I can't find anywhere. 

@alex-s-gardner Can you provide some clarity about which references should be cited for the formulations in `turbulentFlux`? I'd like to make sure they're cited properly in the function header and documentation.

**Comment by alex-s-gardner** [comment]
@NJSchlegel  did some work on the turbulent fluxes so she might have a better lock on the latest version

**Comment by NJSchlegel** [comment]
I am confused.  I thought I deleted the turbulentFlux function (i..e the turbulentFlux file).

**Comment by NJSchlegel** [comment]
Also, I don't know what Bougamont 2006 is.  I suspect that it is actually one of the other Bougamont papers that we ended up referencing in the GEMB manuscript.  I never found the Wright or Dingman paper myself either.  I would stick to the references in the thermo.m function since that is where turbulent flux now comes from and I tried to update the references the comments (though I know you still want to work on fleshing that switch statement out).

**Comment by chadagreene** [comment]
Well if we're deleting `turbulentFlux.m`, then figuring out the references is moot. Shall I delete `turbulentFlux.m`?

**Comment by NJSchlegel** [comment]
I personally don't see the point of having it.  I think turbulent flux should be calculated directly in the thermo loop.  @alex-s-gardner should weigh in though.

**Comment by alex-s-gardner** [comment]
If `turbulentFlux.m` is no longer called then it should be deleted
