### ISSUE TITLE
EI and EW overwritten in melt.m

### ISSUE THREAD

**Issue by chadagreene** [alex-s-gardner/GEMB#22]
[In the `melt.m` function](https://github.com/alex-s-gardner/GEMB/blob/551c22a3c59907b2f66c0b35f72baffaade8db92/GEMB/melt.m#L303-L311), it looks like the variables `EI` and `EW` are managed by `managelayers`, and then immediately overwritten. Here's the section of code I'm talking about: 
```matlab 
% Manage the layering to match the user defined requirements
[d, T, dz, W, mAdd, dz_add, addE, a, adiff, m, EI, EW, re, gdn, gsp] = ...
    managelayers(T, d, dz, W, a, adiff, m, EI, EW, dzMin, zMax, zMin, re, gdn, gsp, zTop, zY, CI, LF, CtoK);

%% CHECK FOR MASS AND ENERGY CONSERVATION

% Calculate final mass [kg] and energy [J]
sumER = Rsum * (LF + CtoK * CI);
EI    = m .* T * CI;
EW    = W .* (LF + CtoK * CI);
```

Is that intentional? My assumption would be that either: 
1. The `managelayers` function should handle doing everything that needs to be done to `EI` and `EW`, or 
2. `EI` and `EW` should be calculated fresh. 

It's odd that `EI` and `EW` are fed into `managelayers`, then taken as outputs from `managelayers`, then immediately overwritten, so I'm wondering if there's a mistake.

**Comment by NJSchlegel** [comment]
#2 is true, EI and EW don't have to be sent and returned by manage layers.  It is just a code relic.
