### ISSUE TITLE
Change input variable names in ISSM version of gridInitialize

### ISSUE THREAD

**Issue by chadagreene** [alex-s-gardner/GEMB#26]
To match [a recent update to the Matlab version](https://github.com/alex-s-gardner/GEMB/commit/ee8b3d2d01238551359f853e1ae2ef2df050088f#diff-120b4e25eba8140b9739cc16e8535456bf3ff70e1ead08dfcda43c3d8a60e931), the input variables to `gridInitialize` need to be changed as follows: 

`zTop` -> `z_top`
`dzTop` -> `dz_top`
`sMax` -> `z_max`
`zY` -> `beta`

The reason for the change is to match the variable names presented in Fig 1 of Gardner et al., 2023. 

Also, you'll notice that I introduced a new optional output `z_center`, which is calculated as: 
```matlab 
% Optional output: 
if nargout>1
    z_center = -cumsum(dz) + dz/2; 
end
```
I'm not sure if `z_center` will be of use to anyone else, but it was helpful for me when creating the [gridInitialize documentation](https://github.com/alex-s-gardner/GEMB/blob/main/Documentation/gridInitialize_documentation.md) to understand what the function does, and perhaps that means it will be useful for others as well.

**Comment by NJSchlegel** [comment]
The variable names have been updated.  z_center was not added into the c++ gridInitialize call since it will not be used currently by that code.
