### ISSUE TITLE
Logical of a sum of a logical in melt.m

### ISSUE THREAD

**Issue by chadagreene** [alex-s-gardner/GEMB#4]
@alex-s-gardner I found an error check in `melt.m` that checks the logical of the sum of a logical. On line [258](https://github.com/alex-s-gardner/GEMB/blob/eed229e46ab77f5cadf7f8b6737c74594a7a9880/GEMB/melt.m#L258C1-L260C8) it reads: 
```matlab
if sum(W < 0.0-Wtol)
```
That works, but it's somewhat unconventional, and I wonder if it's an error. I would expect either: 
```matlab
if any(W < 0.0-Wtol)
```
or 
```matlab
if sum(W) < (0.0-Wtol)
```
The same check appears again on line [302](https://github.com/alex-s-gardner/GEMB/blob/eed229e46ab77f5cadf7f8b6737c74594a7a9880/GEMB/melt.m#L302).

**Comment by alex-s-gardner** [comment]
@chadagreene these types of code specific questions are typically best dealt with through PR with comments. GitHub provides tools for discussion and modification of proposed changes in PRs.

**Comment by alex-s-gardner** [comment]
@chadagreene I agree would propose changing lines 258 and 302 to:
`if any(W < 0.0-Wtol)`
