### ISSUE TITLE
Check ISSM version for dzMin2 inadvertently multipied by zY2 twice

### ISSUE THREAD

**Issue by chadagreene** [alex-s-gardner/GEMB#7]
After fixing this issue in Matlab version, need to check/update ISSM to address the same issue. 

https://github.com/alex-s-gardner/GEMB/issues/6#issue-2409345681

**Comment by NJSchlegel** [comment]
This issue has been pushed to the ISSM main. [commit e068d33](https://github.com/ISSMteam/ISSM/commit/e068d33f28a8b19d599f85531321675112b2f51e)
