### ISSUE TITLE
Grid stretching algorithm in gridInitialize.m

### ISSUE THREAD

**Issue by chadagreene** [alex-s-gardner/GEMB#8]
A [comment](https://github.com/alex-s-gardner/GEMB/blob/0518bfbd88ade378f578e50f125b463eae7f0f89/GEMB/gridInitialize.m#L55) at the bottom of `gridInitialize.m` reads: 
```matlab
%% ---------NEED TO IMPLEMENT A PROPER GRID STRECHING ALGORITHM------------
```
Is this an issue that needs to be addressed, or can I delete this comment and close it out?

**Comment by alex-s-gardner** [comment]
@chadagreene this should probably stay as the current implementation does a ton of allocations which is bad from a compute perspective

**Comment by chadagreene** [comment]
@alex-s-gardner The comment about needing to implement a proper grid stretching algorithm remains in `model_initialize_column`. Still keep the comment there?

**Comment by alex-s-gardner** [comment]
@chadagreene you can delete.. probably should be addressed at some point but things work as is so no need to change anything
